#! /bin/bash

# Display usage information
function usage() {
  echo "Usage: decrypt <vault_id> [file_path]"
  echo "  vault_id: the vault id to use for decryption"
  echo "  file_path: the file or folder to decrypt"
  echo "    if file_path is not provided, all files in **/secrets will be decrypted"
  echo "    if file_path is a file, it will be decrypted"
  echo "    if file_path is a folder, all files in secrets will be decrypted"
}

# Decrypt a single file
function decrypt_file() {
  local file_path=$1
  local output_path="${file_path%.vault}" # remove .vault from file path
  echo "Decrypting $file_path to $output_path"
  cat "$file_path" | ansible-vault decrypt --vault-id "$vault_id" --output "$output_path"
}

# Decrypt all files in a folder
function decrypt_folder() {
  local folder_path=$1
  for file_path in ${folder_path}/*.vault
  do
    decrypt_file "$file_path"
  done
}

# Main script

# Parse arguments
vault_id=$1
input_file_path=$2

# Show help if no arguments are provided
if [ $# -eq 0 ]; then
  usage
  exit 1
fi

# Set file path based on input
if [ -z "$input_file_path" ]; then # if no file path is provided, decrypt all files in **/secrets
  file_path="**/secrets"
  decrypt_folder "$file_path"
else
  if [ -f "$input_file_path" ]; then # if file path is a file, decrypt it
    file_path="$input_file_path"
    decrypt_file "$file_path"
  else # if file path is a folder, decrypt all files in secrets
    file_path="$input_file_path/secrets"
    decrypt_folder "$file_path"
  fi
fi
