#! /bin/bash

DIR="$1/secrets"

for f in ${DIR}/*.yaml.decrypted
do
  echo "Encrypting $f to `echo $f | sed -e 's/\.decrypted$//'`"
  kubeseal <$f >`echo $f | sed -e 's/\.decrypted$//'` --cert $2 -o yaml
done
