prometheus:
  server:
    global:
      external_labels:
        product: "simple"
        environment: "local"
        project: "india"
    ingress:
      enabled: true
      annotations:
        nginx.ingress.kubernetes.io/auth-type: basic
        nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
        nginx.ingress.kubernetes.io/auth-secret: monitoring-basic-auth
      hosts:
        - prometheus-local.simple.org
  alertmanager:
    ingress:
      className: nginx
      enabled: true
      annotations:
        nginx.ingress.kubernetes.io/auth-type: basic
        nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
        nginx.ingress.kubernetes.io/auth-secret: monitoring-basic-auth
      hosts:
        - host: alertmanager-local.simple.org
          paths:
            - path: /
              pathType: ImplementationSpecific
    extraArgs:
      web.external-url: "https://alertmanager-local.simple.org"
      web.route-prefix: "/"
grafana:
  admin:
    existingSecret: "grafana-secrets"
  ingress:
    enabled: true
    hosts:
      - grafana-local.simple.org
  persistence:
    enabled: true
