metabase:
  image:
    tag: v0.62.3
  ingress:
    enabled: true
    className: "nginx"
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    hosts:
      - host: metabase-demo-simpleapp.dghs.gov.bd
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
    - hosts:
      - metabase-demo-simpleapp.dghs.gov.bd
      secretName: metabase-demo-simpleapp.dghs.gov.bd-tls
