{
 "title": "Rails Metrics",
 "time": { "from": "2024-02-16T11:40:56.250Z", "to": "2024-02-16T14:31:32.538Z" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(ruby_rss,namespace)"
    }
   },
   {
    "name": "controller",
    "query": {
     "query": "label_values(ruby_http_requests_total{namespace=\"$namespace\"},controller)"
    }
   },
   {
    "name": "action",
    "query": {
     "query": "label_values(ruby_http_requests_total{namespace=\"$namespace\",controller=~\"$controller\"},action)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(ruby_delayed_jobs_total{namespace=\"$namespace\"},job_name)"
    }
   },
   { "name": "excluded_controllers", "query": "status|healthz" }
  ]
 },
 "panels": [
  {
   "title": "Web Workers",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ruby_rss{type=~'master|web|puma_worker',namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "DJ Workers",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ruby_rss{type='delayed_job',namespace='$namespace'})"
    }
   ]
  },
  {
   "title": "Requests / h",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(ruby_http_requests_total{namespace=\"$namespace\",controller!~\"$excluded_controllers\",controller=~\"$controller\",action=~\"$action\"}[60m]) * 60 * 60)"
    }
   ]
  },
  {
   "title": "Delayed Jobs / h",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(ruby_delayed_job_duration_seconds_summary_count{namespace=\"$namespace\"}[60m]) * 60 * 60)"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Request Duration (all actions)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(irate(ruby_http_request_duration_seconds_sum{namespace=\"$namespace\",controller!~\"$excluded_controllers\",controller=~\"$controller\",action=~\"$action\"}[$__rate_interval])) by (controller, action) / sum(irate(ruby_http_request_duration_seconds_count{namespace=\"$namespace\",controller!~\"$excluded_controllers\",controller=~\"$controller\",action=~\"$action\"}[$__rate_interval])) by (controller, action) * 1000 > 0",
     "legendFormat": "{{controller}}/{{action}}"
    }
   ]
  },
  {
   "title": "Request Count / s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "expr": "sum(rate(ruby_http_request_duration_seconds_count{namespace=\"$namespace\",controller!~\"$excluded_controllers\",controller=~\"$controller\",action=~\"$action\"}[5m])) by (controller,action) > 0",
     "legendFormat": "{{controller}}/{{action}}"
    }
   ]
  },
  {
   "title": "95% Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile(0.95, irate(ruby_http_request_duration_seconds_sum{namespace=\"$namespace\",controller!~\"$excluded_controllers\",controller=~\"$controller\",action=~\"$action\"}[$__rate_interval]) / irate(ruby_http_request_duration_seconds_count{namespace=\"$namespace\",controller!~\"$excluded_controllers\",controller=~\"$controller\",action=~\"$action\"}[$__rate_interval]) > 0)",
     "legendFormat": "95% Request"
    },
    {
     "expr": "quantile(0.95, irate(ruby_http_request_sql_duration_seconds_sum{namespace=\"$namespace\",controller!~\"$excluded_controllers\",controller=~\"$controller\",action=~\"$action\"}[$__rate_interval]) / irate(ruby_http_request_sql_duration_seconds_count{namespace=\"$namespace\",controller!~\"$excluded_controllers\",controller=~\"$controller\",action=~\"$action\"}[$__rate_interval]) > 0)",
     "legendFormat": "95% SQL"
    }
   ]
  },
  {
   "title": "Successful Requests / s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(ruby_http_requests_total{namespace=\"$namespace\",status=~\"^[23].*\",controller!~\"$excluded_controllers\",controller=~\"$controller\",action=~\"$action\"}[5m])) by (status) > 0",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Median Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile(0.5, irate(ruby_http_request_duration_seconds_sum{namespace=\"$namespace\",controller!~\"$excluded_controllers\",controller=~\"$controller\",action=~\"$action\"}[$__rate_interval]) / irate(ruby_http_request_duration_seconds_count{namespace=\"$namespace\",controller!~\"$excluded_controllers\",controller=~\"$controller\",action=~\"$action\"}[$__rate_interval]) > 0)",
     "legendFormat": "Median Request"
    },
    {
     "expr": "quantile(0.5, irate(ruby_http_request_sql_duration_seconds_sum{namespace=\"$namespace\",controller!~\"$excluded_controllers\",controller=~\"$controller\",action=~\"$action\"}[$__rate_interval]) / irate(ruby_http_request_sql_duration_seconds_count{namespace=\"$namespace\",controller!~\"$excluded_controllers\",controller=~\"$controller\",action=~\"$action\"}[$__rate_interval]) > 0)",
     "legendFormat": "Median SQL"
    }
   ]
  },
  {
   "title": "Errors / s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(ruby_http_requests_total{namespace=\"$namespace\",status=~\"^[45].*\",controller=~\"$controller\",action=~\"$action\"}[5m])) by (status) > 0",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Max Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(irate(ruby_http_request_duration_seconds_sum{namespace=\"$namespace\",controller!~\"$excluded_controllers\",controller=~\"$controller\",action=~\"$action\"}[5m]) / irate(ruby_http_request_duration_seconds_count{namespace=\"$namespace\",controller!~\"$excluded_controllers\",controller=~\"$controller\",action=~\"$action\"}[$__rate_interval]) > 0)",
     "legendFormat": "Max Request",
     "target": "carbon.*"
    },
    {
     "expr": "max(irate(ruby_http_request_sql_duration_seconds_sum{namespace=\"$namespace\",controller!~\"$excluded_controllers\",controller=~\"$controller\",action=~\"$action\"}[5m]) / irate(ruby_http_request_sql_duration_seconds_count{namespace=\"$namespace\",controller!~\"$excluded_controllers\",controller=~\"$controller\",action=~\"$action\"}[$__rate_interval]) > 0)",
     "legendFormat": "Max SQL"
    }
   ]
  },
  {
   "title": "Puma",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "sum(ruby_puma_thread_pool_capacity{namespace=\"$namespace\"})",
     "legendFormat": "Free Threads"
    },
    {
     "expr": "sum(ruby_puma_request_backlog{namespace=\"$namespace\"})",
     "legendFormat": "Request Backlog"
    }
   ]
  },
  {
   "title": "Slow Actions (avg/w)",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "topk(10,avg((rate(ruby_http_request_duration_seconds_sum{namespace=~\"$namespace\"}[1w]) / rate(ruby_http_request_duration_seconds_count{namespace=~\"$namespace\"}[1w]))) by (controller, action)) \n"
    }
   ]
  },
  {
   "title": "Most Frequent Actions / Day",
   "type": "table",
   "description": "Average number of requests per day during last week",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "topk(10,sum(rate(ruby_http_request_duration_seconds_count{namespace=~\"$namespace\",controller!~\"$excluded_controllers\"}[1w]) * 3600 * 24) by (controller, action))"
    }
   ]
  },
  {
   "title": "Delayed Jobs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Job Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(ruby_delayed_job_duration_seconds{namespace=\"$namespace\",job_name=~\"$job\"}[$__rate_interval]) / irate(ruby_delayed_jobs_total{namespace=\"$namespace\",job_name=~\"$job\"}[$__rate_interval]) > 0",
     "legendFormat": "{{job_name}}"
    }
   ]
  },
  {
   "title": "Job Count / s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
   "targets": [
    {
     "expr": "irate(ruby_delayed_jobs_total{namespace=\"$namespace\",job_name=~\"$job\"}[$__rate_interval]) > 0",
     "legendFormat": "{{job_name}}"
    }
   ]
  },
  {
   "title": "Max Job Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(irate(ruby_delayed_job_duration_seconds_summary_sum{namespace=\"$namespace\",job_name=~\"$job\"}[$__rate_interval]) / irate(ruby_delayed_job_duration_seconds_summary_count{namespace=\"$namespace\",job=~\"$job\"}[$__rate_interval]) > 0)",
     "legendFormat": "Max. Duration"
    }
   ]
  },
  {
   "title": "Slow Jobs (avg/w)",
   "type": "table",
   "description": "Average duration of last week",
   "gridPos": { "h": 12, "w": 6, "x": 12, "y": 46 },
   "targets": [
    {
     "expr": "topk(10,avg(rate(ruby_delayed_job_duration_seconds{namespace=\"$namespace\"}[1w]) / rate(ruby_delayed_jobs_total{namespace=\"$namespace\"}[1w])) by (job_name))",
     "legendFormat": "Time"
    }
   ]
  },
  {
   "title": "Most Frequent Jobs / Day",
   "type": "table",
   "description": "Number of runs per day during last week",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 46 },
   "targets": [
    {
     "expr": "topk(10,sum(rate(ruby_delayed_jobs_total{namespace=~\"$namespace\"}[1w]) * 3600 * 24) by (job_name))"
    }
   ]
  },
  {
   "title": "Pending/Enqueued Jobs",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "ruby_delayed_jobs_enqueued{namespace=\"$namespace\"}",
     "legendFormat": "enqueued {{queue_name}}"
    },
    {
     "expr": "ruby_delayed_jobs_pending{namespace=\"$namespace\"}",
     "legendFormat": "pending {{queue_name}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory Web",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "ruby_rss{namespace=~\"$namespace\",type=~\"master|web|puma_master|puma_worker\"}",
     "legendFormat": "{{type}} {{hostname}}"
    }
   ]
  },
  {
   "title": "Memory Delayed Job",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "ruby_rss{namespace=~\"$namespace\",type=~\"delayed_job\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Object Allocation Rate Web",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "irate(ruby_allocated_objects_total{namespace=\"$namespace\",type=~\"master|web|puma_master|puma_worker\"}[$__rate_interval])",
     "legendFormat": "{{type}} {{hostname}}"
    }
   ]
  },
  {
   "title": "Object Allocation Rate Delayed Job",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "irate(ruby_allocated_objects_total{namespace=\"$namespace\",type=~\"delayed_job\"}[$__rate_interval])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Heap Web",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "min(ruby_heap_free_slots{namespace=\"$namespace\",type=~\"master|web|puma_master|puma_worker\"}) without (namespace)",
     "legendFormat": "Min Free Slots {{type}} {{hostname}}"
    },
    {
     "expr": "max(ruby_heap_live_slots{namespace=\"$namespace\",type=~\"master|web|puma_master|puma_worker\"}) without (namespace)",
     "legendFormat": "Max Live Slots {{type}} {{hostname}}"
    }
   ]
  },
  {
   "title": "Heap Delayed Job",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "min(ruby_heap_free_slots{namespace=\"$namespace\",type=\"delayed_job\"}) without (pid)",
     "legendFormat": "Min Free Slots {{hostname}}"
    },
    {
     "expr": "max(ruby_heap_live_slots{namespace=\"$namespace\",type=\"delayed_job\"}) without (pid)",
     "legendFormat": "Max Live Slots {{hostname}}"
    }
   ]
  }
 ]
}