---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alertmanager-secrets
  namespace: monitoring
spec:
  encryptedData:
    slack-api-url: AgBRZiVVFaXtp3TD+rxjd9ZqQ9ehWE140HkDF8Rt/yd9mzWy9/RJduKg8b3gyhjplq7hcs1+wGDuR93X3qP6WG/ktgrw2FrTfpwlbEpvV6jExT6vPhViaZHLaLRn9dbmcQU4IYQMOxECln/TBof9wWW5RZCI98yZPTHe9KuuKXDn/VXC1VzsTtyDAjG1y20OxxiCX+fgIES3blkUqCFOOfR0duJUr12UdtFTHtMrRAkOn0a84BFH67p/4KJWbeEhnc3XbeiSgSOc9I0l6FpJ2OFTA3eJoK/pIygzKWjYVyE0SdaN9X/+sqS2IFU1MXYFhVp1X1uHxDMm/FW6gaIIkaSgVii/ve/7JmSt7AJWnwaoAJEYbdxidDkJAaipqAnCP11PDzV5XutUBuCA0gPfx3SCskTFVtsCbQd1Ack0hmTpDEOMCwAVfvelrTHlW1lYQmZZGNtDPvdl5WmDKMsmcAdjz8yUCXSi45b/gkGU8k1BECft7Nd6nSr8shhI+Il+p8huz9n1+TM9Ku4ZtkoFe7iRT5fQ+nA4bm9T+8aWwNBoX67mDlg5FhjVfvr2qzj4W/mwZk1lR0F4qBRtV4fOyPzw7QDEvLVv/8wNyZbDZTxNOeZNPWkVnVIUWe1ge50x9Y3BDsL+siOkgJqrTsx5PvyTD/3lrF1mX98MV77aFbFILDd9Y888BCUPDpFV475djtp8PnrgoqA4aLLmRIQl9qHB
  template:
    metadata:
      creationTimestamp: null
      name: alertmanager-secrets
      namespace: monitoring
    type: Opaque
