apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alertmanager-secrets
  namespace: monitoring
spec:
  encryptedData:
    slack-api-url: AgAPDhMSDQ/fobUFTzFwkxdaSIHiJi9ifrrAbU3wlk5sNOUOPECBgYDg+0RtN8z0OBihPTkoRFN53z3jv0VN7JNZaENNqpUaCb++jT+2oMv9uUqbuF4YyzoVO2WIL+DyqjeAbSIrmq5IyAs8ebxB+vZ0vD49cGmPCv96HCzR/J5mdyJBwfpSEBd0lXdwgPYvHa+/yqHeUWxmnGIizrL5S9dN3iJQ/oGplCsXpAd5t4WLpdQ2gMm4ibd5PG0g3/j/rYr4oCVpH841go3IuOn/7rgdLJh9sjAaKZQRTfx3ZlMiOtO8fRZ1VSDU7EvSWQlwTLlGkCRoVltUYZQhfOzbaHxv7Xjxf/xCpyGWgMe6KgL0nxtBEpF24l32IkQC5YHsaLihcZefLEgVvDSUxQAsRdjJnT6nGfVCrFVX53AzGUnS6xV2M6NXHWbHMiZ9fzME4ArTFpbuk2buhROkK8aK++5gJWBF2Fei0LWE8Indgo/4jZuAjq1EocETz2PFah8Z67nm3ce4nAaD3kvKRezJBTbVC3ujfOkIzxMpypnLFi0LOwienq7daQu+zUr52PHI0VIDbM+p/+vGhuWUhwaHWECLuiX7fCamuq8DE3jV00d2lckqpkAFqUixzrcZKXKx0qTVTXrsEpwkOCXVbCRmqRZ/AFn0Hsn90CvV2ZRKPS5mB8tcClg5//CuhbstLmr/fTHbekunIgHwPSkX2Iq/ypq3
  template:
    metadata:
      creationTimestamp: null
      name: alertmanager-secrets
      namespace: monitoring
    type: Opaque

