---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alertmanager-secrets
  namespace: monitoring
spec:
  encryptedData:
    slack-api-url: AgBoW3d8fqtGo59AAzX0IBzYC0w0VUtCeZg8wpiYEa8q6kU7wTJ5qhrM9dcMmqshFFPL2U444yAHghln9bU1hPftyYGhhqNOwl9VppM6fD19BVxoi6pNmsH8YGe1znLpLSGi/9/UxLKrB0tUr9zRbdyVyt7irIdxDD0gAQ/SMxA4ZAIsbL4fgR6fUi9GflyJMveMW6h3TC/wyluhvghZEfI5/AcZ/Hqv4xWMfHB4B4MvwYqNTid59CgWSYSMxM3icA0RCzUUW3ZtUt04cxJOqBYXgB5DDB5fIwkuc+vgt8bdNtgB65b5evMI7aOVV759gKniOLxVk5FcN4IMTzCkVKeb65JwSHuO2MeS+7CB6p0t5YvoFg2lNv4/5c11w2bpuP8pWChy2Z9RNXgDdFCuhSXaMshbelTtM/HE4C58k6BolE5/K8lGjUG5MI0RD0PQuAYRJEZjRa4k0PFI8eDsDTAyHjmyt8OkFElRmZs9aXSp3LEkffRtzmQJBdsa1lYZYXIav/xP4L88tM2E852PHdSwZzetEF+X29dFQWk3dnysa1dnMMJIqZ6ALubYn2jK7SmaBGJSW8hSOOtxSPvVxdTiuF30Kll+Rxf7HA3Js6RRyUzVufjNSi9gBXE86TDm51mSgv6siyYUiETYB20fsyewJcGjfIC0zZ4kxzxoiuSptCGVvtDgXe3dpHbRevUou4lFL5IdQpHXdAVp0DstDp/p
  template:
    metadata:
      creationTimestamp: null
      name: alertmanager-secrets
      namespace: monitoring
    type: Opaque
