apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-secrets
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAp97BILwD2rU82SCw951wc9a8adKHZO2Ql44LY+oDPOlLJlQH9EDPVIe5RyPMrUN96F74XOjGY7Y4uhFBKJCpa48WsXR/ngeRbPMrhvE+4JI+Q05f2+KvHjZc0wE2X35NcO9YkEt1qEp+Aw3mwc0OPk+tz6Xr3/KWIUQew/MGTnF2wfr88r4LkFo0FRifB7529YqzFw0NZ7FIkt0qPM4Nus3EDYpai6MrR+ymm2MW1tbO4C7jwS+CTG9v2bRShYvKxS1YOAwUKJC+LfDZ6LTaDK3jXAOF/kJ/uy5fTYxLjIfVpaWcTYKJoPcR6f/dL0wM31/3ekQ2ZaGIi2vge82+OfWbz+zoS+O4iTKqmbOCyi9av6e2xaO3UWAhBhO7kSRfFlD/q3u7abfdqJemKFEiBWVScEMKwuNqcTux2jHBiEmGjgrrx6Yg1D0H6xqUV4mcHhQSovNd7ib9imDUTNiVwWweCvpIXiD8SfqdYkYbUaflI0rOesm6R1lxLPxgxYO3ODukr0+tFZLnsKKYDyb4oPfXIZIK/xSU0vMpntTpFJP9O7f3hzNsV65kvkJLtdZM45krx5dX550zCX/Lb/5Vesf2Sk3M2JysLbl2I1oRyZIDgfQ2YnL0ActXe/9k7ckJIEvpc/ewl2NLV5w0haX2/uP1YO2oe/EhQj9VCGIEtWcTPIj3hHdGYFcJQfhXEeAuwX3A1JQ==
    admin-user: AgAK8jP0AcRvnWIGHI5UKhCTxEjl7ZpiXCM2ODfyBqUwewNjDu8VT5WvV3loHESAFCtHJYcbyXiyp49zYmr5HYvUkI/u7GjBm0EpProBpFfchO9T5todDewsyfsRPIn7ILVw2VxRbOlboZzRtENRMT4mdjX8DaGQgLD/4zo1Du3PTu4tm2kZt3RBfoKYN/tbabJvQdS94X3QMY5cpPbTnrQ/I9akppHN+zAeVVcXomGUGuNiplh2VIztCgZdyNthyNV2SDi9r2TsmveNujLgMRT1SDMQYGZysOkID9hOt+d+shDVA/2rhWF/qiYP/UZ78bdYz1nRpkV4DwgfuPDxUhKA2xjQLUkyqIfXzRwktDyNi8Tnp0LvX6cQ7qTij6v3tB+4u8Lzr07+2jD+CzRO0RfmQZREwV1vIwl4XEN7O/wskE3MAzcvB6mJKPZFSwluHedr5ecrZqA/aUksztzIYi0h4/4R9qT7MRXMmjNiokEYi3oc4wj/QQCMxZ3pMmBtgt33ajKV9COkFxo1yiay4X3FKGDFFdVpKBNeGBsHVA74oj+KNkiPDlp+Mz48HqKm/6R2Bg+auv/4XCmhwdtNk0Ba/v3lDJO64oebIm0AipOOKQ/FptGpaW7vA0tr2RYaScpSp6vz7KnUr89/4qumeHolLemXtMWfWh4P9IqWRCt27b0pklU2bIqlReQqYe/wuQg8TeHkEw==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-secrets
      namespace: monitoring
    type: Opaque

