apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-secrets
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAbtSr7WjJe46h6IdVfxntl++awuokIjrRUtrMvGMkZrk3ytPRB9Gk+Gy6YRJS5pRXgMNs3249W8nNpqo9G1dBWuB5+10sCPip9isqAkiIv866lyUwPMeiPwE6PSDpdm+Vqc1SjfLl5ZY2T43rs/rScUuLCme5PwvJqIu54nA11Xx/3kEuldQdUvkfh8AUNRH2BcBfFELYywrJCigDlZyQkTHePBdPSDVmUJZu8m7yUN9KPuZPaop5lMEp8tjuv1rrQINeCLshMo4GAiHD2495Q6hXSdJ1nx4SbjWMFfpDPHZmrwh0ISpkFFaRSN28mdBkV++yAIYxc2C0s/oItq+jHjo+5lv9m6g7sq6bi1m8jiqhSSVV2I0h8BIQnqnon4sfnNI5bBPBSr3pmR2uTSpJcj9/SJGzDuh0DFtcLfxaZyZtKk/Jhf6U/9OG0wYC3OO5M3OmQI2c1VsRvBfSJFOZduDn/LunHiaadsFJmND/NSQhF7p388Nx4Vq+gxFfKTyV2p4+c5QUSEP9VrPE5VTpR6AlbPWfhWDD6SB7648HCbIbwL8i+RfT4DI0kwMxDWIZF9BiNDTPsMLyyzMi1wmLGKxkEiRU4CnTFuZ4jnXmZ7812TMMAsMpe0WtOgIjRjDLKb0mLTeKJ4nwTfcWx6EZqPhuoy8lX4pdddpCoRQO96L8k73RPS9uzthFcHS4SfuZIzM0ClQ==
    admin-user: AgC41fLBmp+FAWw0nGPJoCxoyNde1b52akcmRqVinG4/DPdOCwLPVkkgza8SiB/XIltoKZTMOeQ2RT7nDzcAMPNtIldXYSlqmDLlFpmVlP3lnlzNkbKqdAffDtGFTZ/dfKYbDeMtZtRpCU4kpwo/cnIc+9HUVtf/xDY1VA1haGnTkWAnTVl5Ip79NzvM6D+TfVRR8Y0lHsMhviOBkncYQD/EBi9R57tWEQxskOw1gvYKXJ3l60o/T7w53h07uMdwFBCFytNUir3EYPKIg7uUpDYSAg/jXtRrv1oUKpIJ7i6RCOjTmMUgNM1YOoB3krXfxP/pB3/EmIEDE9gccDCyKoS8+aN+hGRiIbXuhHSUlT6TujRM+P7wWt++iTIH5N6GtAm422qWXIUYXyXSz+0OffpxOwJ/QskdtgRkg4mFB8y1Tymx6kPKqX+dqlQ/63sHoRZ+To5ZGFUuFU4UnPuJqkF5eROumxTiSLC82kmfWmHRDurM+CexwTp9CxA68OAEMuupqmB1AmVwp4CMwtCuUvtvncvmSJ4fADqWVqpg5tvQS46URrmgkuyyjoULlS8tJWsXpQfdcgjcnyF01K7JcoYUSF5XDz7F5uxcp84C6k3O6zQGs7SxCXZDhyJo95entbT41WhTz5dUI8k3hSsqtnRshoqQw7aBZnun026VlFsgZm332/pUn7mvYaV/H+0IZH37AuqXlw==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-secrets
      namespace: monitoring
    type: Opaque

