apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-secrets
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAZanOBtCoenYILxW7i3Wkt9jW3lCYHrAcGNrHLRvO3hNW9LSEknpLR929G05hli7QiSLer9oRq3iHR128Q9Fit+JX/jrpMDE01QZmOIpqMrnRvpNK4chRwqsApFX7DxzQO0VdecJD+R0bcq2QP4ErbX9E17ncmEIopr0SSu48lkalZMXj0u75j5inOMhMdv9FbzScuoIQNhXFb//pGFHXvty7B5G3Vy37Q/zrQGdMABhGuZgTXTCR6TQGS1YA5DqCr85mw+psWsBYth5tVkTGlseZDaJnPh8rYMsbsLtBlzabpF9Q51sreK2gS/0JQNfKID+RL3j9cd4lCrfIbY3MUhTMSF2lj+kSZyUuOZhAB+iYQs4jGI+zXkIfu9ZaO3I9erqh524vMR85zmQDURPYf8dscnqW0/PVLEQw02E06ztZfrYIf+X6zMLO+ln67xT43tBUdcgUjtwQGt7TStuMgVdOXy5EHsgr3dPf8/jzsz9Rh3fD2WyqmheqpJdSPDiWtQkEwll+ms1213wJrMlVAO2K6EIKE3HXG+Bk44gMQJ7zavtZWEQkyYq0yrMA8AtBQmQV5KNPLtsC/PuUnU9R1ME2Z2hpcfIj8p5pCCtZvDdbFNQ+tNkaDFTBmzJ7AyFj4vU2rd0rMBM95jOrnPTjxH9qPo4/U71gC9jvqfD8NBYAU4Ev6SXQfkm9ma2Zh2sPxIxb6zw==
    admin-user: AgBUHCnTV3hT3PBNhFjA5Uj5D54+3+K4UMoEFOHOvZLcmMsUYWNSRetRw+IF+aK+x6e2UUxJ82+lNPJ/ds11Xk5PErLFG5r6MWvqGoeLk6i6olxop9AWlKT8XovXbkhTREFX6lcRQ4u/c8E7Ow32NdV4b7KvSBWnb3v985+E6TUmLe2qdBFfMulJKraVz0gqJYUAB8M2OtPpVCg1N/foaAh/O+kZ3InyGZlHRpTTfRcVqJnfVY3tPhBXQuGLerxq11uFYgIvU15q6hVMHceuAbwoc+0oP9ryg6nXDrQnz0gbQBAschDzmhCe14FZagH0dElZppV3OIuAPLjAWDdJsmBW6lrMkp4Sya7mbju1nHhcZjsx3/ke2C7JdkmgdhHOZgXGFuLFAbj5gvZynx1qD8G5HgqTzSKU965JLXw6DDerV/VBu+UsbAI9PcjTLoDidqQVd2x43gIHrVrZQmVyZnR28YJerIZV2mDH2iNVnrq3JiDmw0bWGQuAd+p5mFpOKycPj9gGpOp+RmyfugceAQBPCFdIfq9Mbj8SutN6HSvok6cdUMf2rRAmlsddRlFcWjBxodkkpRz6180I4TDun5KildTd78R++mxELLkpHz8cMuOA6TSLXrMDj1if7EWBweIykvLOCR29RDgAPjiWd5ybxAaTG8dRrM9xaD0UH3sAhx4O7TmiP3KMnVC9jIrV40lM667YGQ==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-secrets
      namespace: monitoring
    type: Opaque

