---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: monitoring-basic-auth
  namespace: monitoring
spec:
  encryptedData:
    auth: AgCorxzVlbtQriaT7LJ7N56UbDBqoXLq2YFVX+8gZ2ili49DFbQRL6oK3eEkTP3gZho3gXM0p32tmVZbM6LCQ3T71xb62XRAorMFpmlGxZpOTblSN80mpNuKSwouUTHoq600pGBLA55A1RshIZBS27N61DpMGvnsABfEceR9toQdlhN46eoRyKoVJd/rHW9OQIgLsLU5bCJxa1r+yMwrk0l8wTCd5u4mwRZ51v4uUbc5goCZb6w0aWVJhcJykM6mdfsKIZqlnE6RHutCcEd5cVRYhxKoP1GJYMf1g+niauH8VNjpOlVwrwNl9P/7dqqLL+Dlp1O7MJ9rBGAUTwqertz2Si5c4S53QHUE+1tNMvOukvxv6NvOIA8KymKL83VL9d82X2HJgQrnTW1TiheB/bkHSYRJCqOo+6jDGjHwTcIUdgf1V2YCNr7+O25DtAUyO71S8hIeXrC3eeWkxohQFVQqnfIcHmgGXcAC0enRjZyc2pk0uYnasN8C0M0H1PaYmp/AL422j1MFQIRqNyQ5Fv/cR6ZsJLhD5Z8dnL0bxDLc279KsaHCqdU6NdUUtzibILUWUdpamZH5SOXj6va7SiHu61Jm7XzHernZt4OipCXkJQ46Vr5BIdz8WnDBaesAspDePJTv2qsgEHJkAh6XdfwN9cXxrddbnJcyZZpbw5G1YCtXc99UXeyeyatXpjyfraOP8BGHTQ==
  template:
    metadata:
      creationTimestamp: null
      name: monitoring-basic-auth
      namespace: monitoring
    type: Opaque
