ingress:
  enabled: true
  className: "nginx"
  annotations:
    "nginx.ingress.kubernetes.io/configuration-snippet": | 
      proxy_set_header X-Forwarded-Proto https;
      proxy_set_header X-Forwarded-Scheme https;
      proxy_set_header X-Scheme https;
      proxy_set_header X-Forwarded-Port 443;
      proxy_set_header X-Forwarded-Ssl on;
  hosts:
    - host: api-qa.simple.org
      paths:
        - path: /
          pathType: ImplementationSpecific
    - host: dashboard-qa.simple.org
      paths:
        - path: /
          pathType: ImplementationSpecific
server:
  podAnnotations: {
    ad.datadoghq.com/log-tailer.logs: '[{"source": "simple-server","service": "simple-server","tags": ["env:qa"]}]'
  }
worker:
  podAnnotations: {
    ad.datadoghq.com/log-tailer.logs: '[{"source": "simple-server","service": "simple-worker","tags": ["env:qa"]}]'
  }
cron:
  podAnnotations: {
    ad.datadoghq.com/log-tailer.logs: '[{"source": "simple-server","service": "simple-cron","tags": ["env:qa"]}]'
  }
