ingress:
  enabled: true
  className: "nginx"
  annotations:
    "cert-manager.io/cluster-issuer": "letsencrypt-prod"
    "nginx.ingress.kubernetes.io/auth-type": "basic"
    "nginx.ingress.kubernetes.io/auth-secret": "basic-auth"
    "nginx.ingress.kubernetes.io/auth-realm": "Authentication Required"
  hosts:
    - host: api-qa.simple.org
      paths:
        - path: /
          pathType: ImplementationSpecific
    - host: dashboard-qa.simple.org
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
  - hosts:
    - api-qa.simple.org
    secretName: api-qa.simple.org-tls
  - hosts:
    - dashboard-qa.simple.org
    secretName: dashboard-qa.simple.org-tls
ingressSecondary:
  enabled: true
  className: "nginx"
  annotations:
    "cert-manager.io/cluster-issuer": "letsencrypt-prod"
  hosts:
    - host: api-qa-secondary.simple.org
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
  - hosts:
    - api-qa-secondary.simple.org
    secretName: api-qa-secondary.simple.org-tls
