{
 "title": "Spring Boot 2.1 Statistics",
 "description": "Dashboard for Spring Boot2.1 Statistics(based on Spring Boot2 Statistic by micrometer-prometheus).",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(jvm_info,namespace)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(jvm_classes_loaded_classes{namespace=\"$namespace\"},instance)"
    }
   },
   {
    "name": "memory_pool_heap",
    "label": "Memory Pool (heap)",
    "query": "label_values(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"heap\"},id)"
   },
   {
    "name": "memory_pool_nonheap",
    "label": "Memory Pool (nonheap)",
    "query": "label_values(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"nonheap\"},id)"
   }
  ]
 },
 "panels": [
  {
   "title": "Basic Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Heap Used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{ instance=\"$instance\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{instance=\"$instance\", area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Non-Heap Used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{ instance=\"$instance\", area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{instance=\"$instance\", area=\"nonheap\"})"
    }
   ]
  },
  {
   "title": "Process Open Files",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "process_files_open_files{instance=\"$instance\"}",
     "legendFormat": "Open Files"
    },
    {
     "expr": "process_files_max_files{instance=\"$instance\"}",
     "legendFormat": "Max Files"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{instance=\"$instance\"}*1000"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_cpu_usage{instance=\"$instance\"}",
     "legendFormat": "System CPU Usage"
    },
    {
     "expr": "process_cpu_usage{instance=\"$instance\"}",
     "legendFormat": "Process CPU Usage"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_load_average_1m{instance=\"$instance\"}",
     "legendFormat": "Load Average [1m]"
    },
    {
     "expr": "system_cpu_count{instance=\"$instance\"}",
     "legendFormat": "CPU Core Size"
    }
   ]
  },
  {
   "title": "JVM Statistics - Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$memory_pool_heap (heap)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "repeat": "memory_pool_heap",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{instance=\"$instance\", id=\"$memory_pool_heap\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_committed_bytes{instance=\"$instance\",  id=\"$memory_pool_heap\"}",
     "legendFormat": "Commited"
    },
    {
     "expr": "jvm_memory_max_bytes{instance=\"$instance\",  id=\"$memory_pool_heap\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Classes Unloaded",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(jvm_classes_unloaded_classes_total{instance=\"$instance\"}[5m])",
     "legendFormat": "Classes Unloaded"
    }
   ]
  },
  {
   "title": "$memory_pool_nonheap (non-heap)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "repeat": "memory_pool_nonheap",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{instance=\"$instance\", id=\"$memory_pool_nonheap\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_committed_bytes{instance=\"$instance\", id=\"$memory_pool_nonheap\"}",
     "legendFormat": "Commited"
    },
    {
     "expr": "jvm_memory_max_bytes{instance=\"$instance\",  id=\"$memory_pool_nonheap\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Mapped Buffers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_memory_used_bytes{instance=\"$instance\", id=\"mapped\"}",
     "legendFormat": "Used Bytes"
    },
    {
     "expr": "jvm_buffer_total_capacity_bytes{instance=\"$instance\", id=\"mapped\"}",
     "legendFormat": "Capacity Bytes"
    }
   ]
  },
  {
   "title": "Classes Loaded",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_loaded_classes{instance=\"$instance\"}",
     "legendFormat": "Classes Loaded"
    }
   ]
  },
  {
   "title": "Memory Allocate/Promote",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(jvm_gc_memory_allocated_bytes_total{instance=\"$instance\"}[5m])",
     "legendFormat": "allocated"
    },
    {
     "expr": "irate(jvm_gc_memory_promoted_bytes_total{instance=\"$instance\"}[5m])",
     "legendFormat": "promoted"
    }
   ]
  },
  {
   "title": "Direct Buffers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_memory_used_bytes{instance=\"$instance\", id=\"direct\"}",
     "legendFormat": "Used Bytes"
    },
    {
     "expr": "jvm_buffer_total_capacity_bytes{instance=\"$instance\",  id=\"direct\"}",
     "legendFormat": "Capacity Bytes"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_daemon_threads{instance=\"$instance\"}",
     "legendFormat": "Daemon"
    },
    {
     "expr": "jvm_threads_live_threads{instance=\"$instance\"}",
     "legendFormat": "Live"
    },
    {
     "expr": "jvm_threads_peak_threads{instance=\"$instance\"}",
     "legendFormat": "Peak"
    }
   ]
  },
  {
   "title": "JVM Statistics - GC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {}
   ]
  },
  {
   "title": "GC Count",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "irate(jvm_gc_pause_seconds_count{instance=\"$instance\"}[5m])",
     "legendFormat": "{{action}} [{{cause}}]"
    }
   ]
  },
  {
   "title": "GC Stop the World Duration",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(jvm_gc_pause_seconds_sum{instance=\"$instance\"}[5m])",
     "legendFormat": "{{action}} [{{cause}}]"
    }
   ]
  },
  {
   "title": "HTTP Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Request Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(http_server_requests_seconds_count{instance=\"$instance\", uri!~\".*actuator.*\"}[5m])",
     "legendFormat": "{{method}} [{{status}}] - {{uri}}"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(http_server_requests_seconds_sum{instance=\"$instance\",  exception=\"None\", uri!~\".*actuator.*\"}[5m]) / irate(http_server_requests_seconds_count{instance=\"$instance\",  exception=\"None\", uri!~\".*actuator.*\"}[5m])",
     "legendFormat": "{{method}} [{{status}}] - {{uri}}"
    }
   ]
  }
 ]
}