{
 "title": "Tomcat dashboard (for Prometheus Operator)",
 "description": "Tomcat dashboard using metrics from prometheus JMX exporter",
 "tags": [ "Tomcat8" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Job",
    "query": "label_values(tomcat_serverinfo, namespace)"
   },
   {
    "name": "service",
    "query": "label_values(tomcat_serverinfo{namespace=\"$namespace\"}, service)"
   },
   {
    "name": "pod",
    "label": "pod",
    "query": "label_values(tomcat_serverinfo{namespace=\"$namespace\", service=\"$service\"}, pod)"
   },
   {
    "name": "protocol",
    "query": "label_values(tomcat_bytesreceived_total{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\"}, protocol)"
   }
  ]
 },
 "panels": [
  {
   "title": "Server info",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tomcat_serverinfo{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Protocol [$protocol]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "repeat": "protocol",
   "targets": [
    {}
   ]
  },
  {
   "title": "Max threads",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 2, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tomcat_threadpool_maxthreads{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\",protocol=\"$protocol\"}"
    }
   ]
  },
  {
   "title": "Min spare threads",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tomcat_threadpool_minsparethreads{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\",protocol=\"$protocol\"}"
    }
   ]
  },
  {
   "title": "Accept count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tomcat_threadpool_acceptcount{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\",protocol=\"$protocol\"}"
    }
   ]
  },
  {
   "title": "Acceptor thread count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tomcat_threadpool_acceptorthreadcount{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\",protocol=\"$protocol\"}"
    }
   ]
  },
  {
   "title": "Poller thread count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tomcat_threadpool_pollerthreadcount{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\",protocol=\"$protocol\"}"
    }
   ]
  },
  {
   "title": "Traffic send/recv",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "increase(tomcat_bytesreceived_total{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\", protocol=\"$protocol\"}[$__interval])",
     "legendFormat": "Received {{protocol}}[{{port}}]"
    },
    {
     "expr": "increase(tomcat_bytessent_total{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\", protocol=\"$protocol\"}[$__interval])",
     "legendFormat": "Sent {{protocol}}[{{port}}]"
    }
   ]
  },
  {
   "title": "Request  count / error count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(tomcat_requestcount_total{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\",protocol=\"$protocol\"}[$__interval])",
     "legendFormat": "Request {{protocol}}[{{port}}]"
    },
    {
     "expr": "increase(tomcat_errorcount_total{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\",protocol=\"$protocol\"}[$__interval])",
     "legendFormat": "Error {{protocol}}[{{port}}]"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tomcat_threadpool_currentthreadcount{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\", protocol=\"$protocol\"}",
     "legendFormat": "current {{protocol}}[{{port}}]"
    },
    {
     "expr": "tomcat_threadpool_currentthreadsbusy{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\", protocol=\"$protocol\"}",
     "legendFormat": "current busy  {{protocol}}[{{port}}]"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tomcat_threadpool_connectioncount{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\", protocol=\"$protocol\"}",
     "legendFormat": "connection  {{protocol}}[{{port}}]"
    },
    {
     "expr": "tomcat_threadpool_keepalivecount{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\", protocol=\"$protocol\"}",
     "legendFormat": "keep alive  {{protocol}}[{{port}}]"
    }
   ]
  },
  {
   "title": "Servlet Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Session count",
     "type": "graph",
     "gridPos": { "h": 9, "w": 20, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(increase(tomcat_session_sessioncounter_total{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\"}[$__interval])) by (instance)",
       "legendFormat": "New"
      },
      {
       "expr": "sum(increase(tomcat_session_expiredsessions_total{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\"}[$__interval])) by (instance)",
       "legendFormat": "Expired"
      },
      {
       "expr": "sum(increase(tomcat_session_rejectedsessions_total{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\"}[$__interval])) by (instance)",
       "legendFormat": "Rejected"
      }
     ]
    },
    {
     "title": "Session current count",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(tomcat_session_sessioncounter_total{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\"} - tomcat_session_expiredsessions_total)"
      }
     ]
    },
    {
     "title": "Session total created",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(tomcat_session_sessioncounter_total{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\"})"
      }
     ]
    },
    {
     "title": "Session total expired",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(tomcat_session_expiredsessions_total{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\"})"
      }
     ]
    },
    {
     "title": "Top 5 servlet request count",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(5, increase(tomcat_servlet_requestcount_total{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\"}[$__interval]))",
       "legendFormat": "module={{module}} servlet={{servlet}}"
      }
     ]
    },
    {
     "title": "Top 5 servlet error count",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(5, increase(tomcat_servlet_errorcount_total{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\"}[$__interval]))",
       "legendFormat": "module={{module}} servlet={{servlet}}"
      }
     ]
    },
    {
     "title": "Top 5 servlets average processing time per request",
     "type": "graph",
     "description": "Top 4 servlets average processing time per request in last 5 minutes",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "topk(5, increase(tomcat_servlet_processingtime_total{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\"}[$__interval]) / increase(tomcat_servlet_requestcount_total[$__interval]))",
       "legendFormat": "module {{module}} servlet {{servlet}}"
      }
     ]
    }
   ]
  }
 ]
}