---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: loki-basic-auth
  namespace: loki
spec:
  encryptedData:
    auth: AgBf+vOHVhcTQhgA6YdJb/ztQBMYVlCUS4fFa3bGQLmpQtpdXLfSCCtiHy4b60As2a8kmSK9oN6bj18SjOhbopRMZ75zcqBWzBArJJX+EeyMFzR2eGeelNnYsPMnCkeuRQ5GPt4zTX5ER1LHz5f7tGfw5+Ti4YufTsy6byDdXC+4Qs+GMagx11+75nvIWuZp+wr3VLgo/7enEPoI/nAD1twaggNM62Ar9R/ToBrK8cu4ZQz2GE9GN9ohcMF5tAvpVUyk2CXrolx74h0brg8inxPeIjOb6wDiYGaxXVVk4Com6ID3n6usxm6ypFoWugEiZjOHkESo3JrSw8tm7CoB6xcyX8js9hWOjvkiLAqDo+/QxEfJdeYSFrZ82gQpgQgYmcGoa2UOLXNxXMPy5hHum1JVS33DKvgSREcbXApjW6pQuOwnzuq2HrmOdBsndf2hiiAAk9Ufy0HoQt0oztRCrqavZRfF2qX6W8HKYm7OYbe8zpBijKiFcVSX9x5z6TKmxo5aZIK80/H0CtNeBzCCnjW+aIWJdEuvNgFTogCohz9f3ukhCiQgOuyAJK8qTHzl4EPQmYFWYLdLAnFtTft/lcRJwEvPgA+ZU1jC42fJLfsFT2CKwFCemIWWGzOh0SXkH4KMKX/Bx39hYs3RGeiZln3yehVfRjRESDfABC5s3zWHNAHier7MpRlyGZEyvv+UUxp4keX5jiK1WHphIzxUlqY39+1/9I1KKXHF7aJDQO5SrJx3ExSoklgCI7fzgTDs4tJnU+Vw5Obzdg==
  template:
    metadata:
      creationTimestamp: null
      name: loki-basic-auth
      namespace: loki
    type: Opaque
