---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: loki-secrets
  namespace: loki
spec:
  encryptedData:
    LOKI_S3_ACCESKEYID: AgCfg8USo+vFVPDRsT1I3Ia6tQc0eajmveXhbTvfzObq33VBZYouwfaaPjXEyYcmrYGqXzbN/sisCDh2H7D2e4zrqw+G1V6+7NgmHZ2MnsSNjstRl0EaELxAy4sAOtg+ToQ6CpuGekrsJyGS+AJxMhQWN3+/mYArH4c4QKtiHN55KRTNRNw1a/vvyOQNMcv2A2o8vhNPQl7hJgz5xy7WDmpHVVtcxhjrwDRlkUEQAZ/nMp0BrJslL2AH6Fherb8wts98Y374lYP7tbAm6CXNelhT9JSnhYp6NG8NWzgy0QzegO6wxA5DxQ06uh3h0N5gCSxwbjnOWesjVb6xA12KtYWhOTKAzWvt0SrNrBy1KG/kQbVo8au1df0n0Xs1wrMqnJOV16s7yyWgV3vb4eSSOfRRmvqgzx4ZFBqk0YF6qhi9K9M5cezSoou7ejVagLWGMZbfofin+Ra+hE37FmbI/Lj/pBV2hQYSZbEwkcXgaOvZL4WimyRQm+OR/7BLhLy7Lee7mw9km8HEIkWOVlRIQYh7JWigwzLoLoBGREvcPxLOlQwP2bLgfNZfMwoCta1uG9/IE0i4VD94z9yYsY5AfCZQQErnMa4kq0TpB2d+6KR5pKn8VnjEgjGpUHKSF2FGDdXnq4ZPOwrutb4nbxlZfAKhN5zKNmA+Eb+r9RqaEEdwhA/TTM2WAGNZAMjbDg88NTyvz+O74x2NUVUfPgVB7RPmBeW7xQ==
    LOKI_S3_SECRETACCESSKEY: AgCtF8uVGy0UPiBx4Gq/CnTHvHKtLgNmtxJ2iuQLYD/quNbxV30rlQcKj2EiUPmcnKYVXA5mbFmHfdsb58BtGKMXW/8OxP+8HstEQmdIgBK0qX1fHync4LIlah5BKz4sFkc/jHljvynW4EMcWivspFEGVPULYSO6+Z5BGJ3v2m5ly7IFC6D+AM3JzLIp8Etz9FLMlSa2sf5m1wfJgnchnnAy00MYAEn53DX0JYS8UjbO82pEy9QegRDaRCDE+pqXzpVvmqpuZ2gB0LGywQFXPAORv1nXNJ29tf0YWlFVB18ZGoOFVBV2uag0vNQ+cJDG7t9Sna3bc46+HU6bAQvyjoqhfXfsQhu+SVzXoUOmNPRtokcIltw8OzxXz5gIjFdjHEIZAXYulwgn/j2vs28Jd+xNeWxrDiVTfR/+iZlYjeMA2TkH6yjWSz0ex/vcA97jYbs7VvmWFtgF74EUiQZSCk7nlmCP7Vo0KVKnJG9LndLrcEooE2kmVLlQ2lXEx+4JelLE4gQ5RqB1oLatORdt9wNXCcWmO8PbE7420MV2APCaAi4inVHC80bQdPWshOf6ChXaHPGKgb8MifGRKmK0mor0ZJr5G0we0XGhfaoxmk/oUiRYO8ZYXTr1F6YLEo4t4tcyJH4AxpJ4cMjcJ0Lva3nmack7sM0cMlLaUTY3TBQUn9wOPY1M4yUSaAhFzmNbWkITtcKErM7YvxqnI3tIDVdrMnOvCnH10eWBiysqArOsdrkuOrkde3fvFA==
  template:
    metadata:
      creationTimestamp: null
      name: loki-secrets
      namespace: loki
    type: Opaque
