apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dhis2
  namespace: test-wal-issue
spec:
  encryptedData:
    s3.conf: AgAhNpub4S+vUrZ5J4x4ibILvA9hnW/NurFG+NHc6LaTOqa9fquSvsxt7m7r+dASInY6dY7OBA37R1jo1ygdT/TIw/PVK9cD3v8kHEHu+pM8B0kFFe3Dmx5LzfAzw06XDCeSwak+XmeVtLN3MJKDxoGsTiYuv7gjCGhekvF041YrETcv2TuasB37+91QLvclyMYaCnJw8MtELWJgHldJCiLu99SXUFRwakPnEj/rw0hOCjYTdF6WjkD3TKkiSp7r68Ivi7gV6Dk0FC5+A+vBjMgqqtz4gDYXhwi6HiGQ9eMGWY84QAixaCbB1Eo3ARGw+y+dTE14HPlIV8x/y8pEo4S6TYZ8cGk51vFZLYq56ucVa+j7NyI8cuTA1OdUj7q2PmH+EUvJFAbyP/MAKy8tbESyXbMMxypiocUlViz8sDdswJWQvjBGKW7mlX6/h2/d+mTSbHNqdjbtjWBGecG7EgYd+O/4KsWtmrlhhOPsvHAPA2GUpmpIdHYr6zdSlgQu2aRfLnkmXjwDpEVRCJBNg0m5SPb26c9Mhdlh9dyOX4I8uNlbQwdEi4hNEgn+fkoVu6MfYvfDcZGwpESjHB1TAf0tcS8MxNzUcCu35Ic+p3fVwFIW9Iv8n+RQSEVrTHTSQMUH5MJCaUxnAb8KJM2pwzX9raT1/G6Fn5maTIe+C0Ru27p3aKqR/7VsCTms1JZZqFHm0F0q3CmzfO9T2v3hbgYdnocrGxli+p1Ck6dYGOV6MnLYsJv+VZlq0lTuiqGVke2d+L2g7lkSpCXCS+GO1Q7D+WmURraS7Yw1IA0cqHd0YNP6OEy+h9/EUm3KCxQMmrk8XO12Dcmj
  template:
    metadata:
      creationTimestamp: null
      name: dhis2
      namespace: test-wal-issue
    type: Opaque

